import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // {
    //     key: 'dashboard',
    //     path: '/dashboard',
    //     title: 'Dashboard',
    //     translateKey: 'nav.dashboard',
    //     icon: 'home',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'empSplTax',
    //     path: '/empSplTax',
    //     title: 'Employee Special Tax',
    //     translateKey: 'nav.empSplTax',
    //     icon: 'cash',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },

    {
        key: 'Settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.collapseMenu.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.ViewSettings',
                path: '/ViewSettings',
                title: 'System Variables',
                translateKey: 'nav.collapseMenu.ViewSettings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.Development',
                path: '/settings/ResetData/Development',
                title: 'Development',
                translateKey: 'nav.collapseMenu.Development',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },

    {
        key: 'settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.ViewSettings',
                path: '/ViewSettings',
                title: 'System Variables',
                translateKey: 'nav.collapseMenu.ViewSettings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.resetData',
                path: '/settings/ResetData/Development',
                title: 'Reset Data',
                translateKey: 'nav.collapseMenu.resetData',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    /** Example purpose only, please remove */
    {
        key: 'paycodes',
        path: '/paycodes',
        title: 'Pay Codes',
        translateKey: 'nav.paycodes',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'Calculations',
        path: '',
        title: 'Calculations',
        translateKey: 'nav.collapseMenu.calculations',
        icon: 'calculator',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.calculations',
                path: '/calculations',
                title: 'Calculations',
                translateKey: 'nav.collapseMenu.calculations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.taxCalculations',
                path: '/tax/Calculations/calculations',
                title: 'Tax Calculations',
                translateKey: 'nav.collapseMenu.taxCalculations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'PayrollProcess',
        path: '',
        title: 'Payroll Process',
        translateKey: 'nav.collapseMenu.payrollProcess',
        icon: 'process',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.DataVerification',
                path: '/DataVerification',
                title: 'Data Verification',
                translateKey: 'nav.collapseMenu.DataVerification',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.ProcessPayroll',
                path: '/ProcessPayroll',
                title: 'Process Payroll',
                translateKey: 'nav.collapseMenu.ProcessPayroll',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.BankTransfer',
                path: '/BankTransfer',
                title: 'Bank Transfer',
                translateKey: 'nav.collapseMenu.BankTransfer',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.payrunSummary',
                path: '/PayrunSummary',
                title: 'Payrun Summary',
                translateKey: 'nav.collapseMenu.payrunSummary',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'PaysheetPrint',
        path: '',
        title: 'Paysheet Print',
        translateKey: 'nav.collapseMenu.paysheetPrint',
        icon: 'print',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.paysheet',
                path: '/Paysheet',
                title: 'Paysheet Print',
                translateKey: 'nav.collapseMenu.paysheet',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.printbyEpf',
                path: '/PaysheetPrint',
                title: 'Print By EPF',
                translateKey: 'nav.collapseMenu.printbyEpf',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'Users',
        path: '',
        title: 'Users',
        translateKey: 'nav.collapseMenu.users',
        icon: 'users',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.ViewUsers',
                path: '/ViewUsers',
                title: 'User Accounts',
                translateKey: 'nav.collapseMenu.ViewUsers',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'User'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'Reports',
        path: '',
        title: 'Reports',
        translateKey: 'nav.collapseMenu.reposts',
        icon: 'reports',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.payrollSummary',
                path: '/PayrollSummary',
                title: 'Payroll Summary',
                translateKey: 'nav.collapseMenu.payrollSummary',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.UnrecoveredList',
                path: '/UnrecoveredList',
                title: 'Unrecovered List',
                translateKey: 'nav.collapseMenu.UnrecoveredList',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.LumpSumTaxReport',
                path: '/LumpSumTaxReport',
                title: 'Lump-Sum Tax Report',
                translateKey: 'nav.collapseMenu.LumpSumTaxReport',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.PayCodeWiseReport',
                path: '/PayCodeWiseReport',
                title: 'Pay Code Wise Data Report',
                translateKey: 'nav.collapseMenu.PayCodeWiseReport',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'helpcenter',
        path: '',
        title: 'Help Center',
        translateKey: 'nav.collapseMenu.helpcenter',
        icon: 'helpcenter',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.knowledgebase',
                path: '/knowledgebase',
                title: 'Knowledge Base',
                translateKey: 'nav.collapseMenu.knowledgebase',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.articleadd',
                path: '/knowledgebase/Article/articleadd',
                title: 'Add Article',
                translateKey: 'nav.collapseMenu.articleadd',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Group Menu',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: '',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Group single menu item',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'Menu item 1',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'Menu item 2',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig
