import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import appsNavigationConfig from './apps.navigation.config'
import {
    ADMIN,
    FIADMIN,
    FIEX1,
    FIEX2,
    SECADMIN,
    SECUSER,
    SUPERVISOR,
    USER,
} from '@/constants/roles.constant'

const navigationConfig: NavigationTree[] = [
    // ...appsNavigationConfig,
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Admin', FIADMIN],
        subMenu: [],
    },
    // {
    //     key: 'UserDashboard',
    //     path: '/UserDashboard',
    //     title: 'Home',
    //     translateKey: 'nav.UserDashboard',
    //     icon: 'home',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: ['User', 'Supervisor'],
    //     subMenu: [],
    // },
    {
        key: 'UserDashboard',
        path: '/UserDashboard',
        title: 'MyLeave',
        translateKey: 'nav.UserDashboard',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'appsLeave.LeaveTypes',
        path: '/LeaveTypes',
        title: 'Leave Types',
        translateKey: 'nav.LeaveTypes',
        icon: 'finePrint',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'appsLeave.Supervisor',
        path: '/Supervisor',
        title: 'Supervisor',
        translateKey: 'nav.Supervisor',
        icon: 'manager',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Supervisor'],
        subMenu: [],
    },
    {
        key: 'appsLeave.AssignApprovalLevels',
        path: '/AssignApprovalLevels',
        title: 'Assign Approval Levels',
        translateKey: 'nav.AssignApprovalLevels',
        icon: 'treeStructure',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Supervisor'],
        subMenu: [],
    },
    {
        key: 'appsLeave.LeaveApprove',
        path: '/LeaveApprove',
        title: 'Approve Leave Request',
        translateKey: 'nav.LeaveApprove',
        icon: 'clock',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['User', 'Supervisor'],
        subMenu: [],
    },
    {
        key: 'AdvanceRequest',
        path: '/AdvanceRequest',
        title: 'Advance Payment Request',
        translateKey: 'nav.AdvanceRequest',
        icon: 'money',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['User', 'Supervisor'],
        subMenu: [],
    },
    {
        key: 'CircuitBungalow',
        path: '',
        title: 'Circuit Bungalow',
        translateKey: 'nav.collapseMenu.CircuitBungalow',
        icon: 'bungalow',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.CircuitBungalow',
                path: '/CircuitBungalow',
                title: 'Circuit Bungalow',
                translateKey: 'nav.collapseMenu.CircuitBungalow',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', SECADMIN],
                subMenu: [],
            },
            {
                key: 'collapseMenu.Reservation',
                path: '/Reservation',
                title: 'Bungalow Reservation',
                translateKey: 'nav.collapseMenu.Reservation',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.ReservationPayments',
                path: '/ReservationPayments',
                title: 'Reservation Payments',
                translateKey: 'nav.collapseMenu.ReservationPayments',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', SECADMIN, SECUSER],
                subMenu: [],
            },
            {
                key: 'collapseMenu.RaffleDraw',
                path: '/RaffleDraw',
                title: 'Raffle Draw Results',
                translateKey: 'nav.collapseMenu.RaffleDraw',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', SECADMIN, SECUSER],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'empSplTax',
    //     path: '/empSplTax',
    //     title: 'Employee Special Tax',
    //     translateKey: 'nav.empSplTax',
    //     icon: 'cash',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },

    {
        key: 'Settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.collapseMenu.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['Admin'],
        subMenu: [
            {
                key: 'collapseMenu.ViewSettings',
                path: '/ViewSettings',
                title: 'System Variables',
                translateKey: 'nav.collapseMenu.ViewSettings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.Development',
                path: '/settings/ResetData/Development',
                title: 'Development',
                translateKey: 'nav.collapseMenu.Development',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.ScheduleJobs',
                path: '/configurations/ScheduleJobs/ScheduleJobs',
                title: 'Backgroud Jobs',
                translateKey: 'nav.collapseMenu.ScheduleJobs',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'Payments',
        path: '/Payments',
        title: 'Other Payments',
        translateKey: 'nav.Payments',
        icon: 'manager',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Admin', FIADMIN, FIEX1],
        subMenu: [],
    },
    // {
    //     key: 'settings',
    //     path: '',
    //     title: 'Settings',
    //     translateKey: 'nav.settings',
    //     icon: 'settings',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: ['Admin'],
    //     subMenu: [
    //         {
    //             key: 'collapseMenu.ViewSettings',
    //             path: '/ViewSettings',
    //             title: 'System Variables',
    //             translateKey: 'nav.collapseMenu.ViewSettings',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: ['Admin'],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapseMenu.resetData',
    //             path: '/settings/ResetData/Development',
    //             title: 'Reset Data',
    //             translateKey: 'nav.collapseMenu.resetData',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: ['Admin'],
    //             subMenu: [],
    //         },
    //     ],
    // },
    /** Example purpose only, please remove */
    {
        key: 'paycodes',
        path: '/paycodes',
        title: 'Pay Codes',
        translateKey: 'nav.paycodes',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, FIADMIN],
        subMenu: [],
    },
    {
        key: 'Calculations',
        path: '',
        title: 'Calculations',
        translateKey: 'nav.collapseMenu.calculations',
        icon: 'calculator',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, FIADMIN],
        subMenu: [
            {
                key: 'appsPayroll.calculations',
                path: '/calculations',
                title: 'Calculations',
                translateKey: 'nav.collapseMenu.calculations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN],
                subMenu: [],
            },
            {
                key: 'appsPayroll.taxCalculations',
                path: '/tax/Calculations/calculations',
                title: 'Tax Calculations',
                translateKey: 'nav.collapseMenu.taxCalculations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'PayrollProcess',
        path: '',
        title: 'Payroll Process',
        translateKey: 'nav.collapseMenu.payrollProcess',
        icon: 'process',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, FIADMIN],
        subMenu: [
            {
                key: 'collapseMenu.DataVerification',
                path: '/DataVerification',
                title: 'Data Verification',
                translateKey: 'nav.collapseMenu.DataVerification',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
            {
                key: 'collapseMenu.ProcessPayroll',
                path: '/ProcessPayroll',
                title: 'Process Payroll',
                translateKey: 'nav.collapseMenu.ProcessPayroll',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
            {
                key: 'collapseMenu.BankTransfer',
                path: '/BankTransfer',
                title: 'Bank Transfer',
                translateKey: 'nav.collapseMenu.BankTransfer',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
            {
                key: 'collapseMenu.payrunSummary',
                path: '/PayrunSummary',
                title: 'Payrun Summary',
                translateKey: 'nav.collapseMenu.payrunSummary',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
        ],
    },
    {
        key: 'PaysheetView',
        path: '/PaysheetView',
        title: 'Paysheet View',
        translateKey: 'nav.PaysheetView',
        icon: 'print',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [
            ADMIN,
            FIADMIN,
            FIEX1,
            FIEX2,
            SECADMIN,
            SECUSER,
            SUPERVISOR,
            USER,
        ],
        subMenu: [],
    },
    {
        key: 'Users',
        path: '',
        title: 'Users',
        translateKey: 'nav.collapseMenu.users',
        icon: 'users',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['Admin'],
        subMenu: [
            {
                key: 'collapseMenu.ViewUsers',
                path: '/ViewUsers',
                title: 'User Accounts',
                translateKey: 'nav.collapseMenu.ViewUsers',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'User'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'Reports',
        path: '',
        title: 'Reports',
        translateKey: 'nav.collapseMenu.reposts',
        icon: 'reports',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, FIADMIN, FIEX1],
        subMenu: [
            {
                key: 'collapseMenu.payrollSummary',
                path: '/PayrollSummary',
                title: 'Payroll Summary',
                translateKey: 'nav.collapseMenu.payrollSummary',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
            {
                key: 'collapseMenu.UnrecoveredList',
                path: '/UnrecoveredList',
                title: 'Unrecovered List',
                translateKey: 'nav.collapseMenu.UnrecoveredList',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
            {
                key: 'collapseMenu.LumpSumTaxReport',
                path: '/LumpSumTaxReport',
                title: 'Lump-Sum Tax Report',
                translateKey: 'nav.collapseMenu.LumpSumTaxReport',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
            {
                key: 'collapseMenu.PayCodeWiseReport',
                path: '/PayCodeWiseReport',
                title: 'Pay Code Wise Data Report',
                translateKey: 'nav.collapseMenu.PayCodeWiseReport',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
            {
                key: 'collapseMenu.AdvancePayment',
                path: '/AdvancePayment',
                title: 'Advance Payment Report',
                translateKey: 'nav.collapseMenu.AdvancePayment',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, FIADMIN, FIEX1],
                subMenu: [],
            },
        ],
    },
    {
        key: 'helpcenter',
        path: '',
        title: 'Help Center',
        translateKey: 'nav.collapseMenu.helpcenter',
        icon: 'helpcenter',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.knowledgebase',
                path: '/knowledgebase',
                title: 'Knowledge Base',
                translateKey: 'nav.collapseMenu.knowledgebase',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.articleadd',
                path: '/knowledgebase/Article/articleadd',
                title: 'Add Article',
                translateKey: 'nav.collapseMenu.articleadd',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Group Menu',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: '',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Group single menu item',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'Menu item 1',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'Menu item 2',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig
