import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'empSplTax',
        path: '/empSplTax',
        title: 'Employee Special Tax',
        translateKey: 'nav.empSplTax',
        icon: 'cash',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'calculations',
        path: '/calculations',
        title: 'Calculations',
        translateKey: 'nav.calculations',
        icon: 'cash',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Admin'],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    {
        key: 'paycodes',
        path: '/paycodes',
        title: 'Pay Codes',
        translateKey: 'nav.paycodes',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'Calculations',
        path: '',
        title: 'Calculations',
        translateKey: 'nav.collapseMenu.calculations',
        icon: 'calculator',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.calculations',
                path: '/calculations',
                title: 'Calculations',
                translateKey: 'nav.collapseMenu.calculations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.taxCalculations',
                path: '/tax/Calculations/calculations',
                title: 'Tax Calculations',
                translateKey: 'nav.collapseMenu.taxCalculations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'PayrollProcess',
        path: '',
        title: 'Payroll Process',
        translateKey: 'nav.collapseMenu.payrollProcess',
        icon: 'cash',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.DataVerification',
                path: '/DataVerification',
                title: 'Data Verification',
                translateKey: 'nav.collapseMenu.DataVerification',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.ProcessPayroll',
                path: '/ProcessPayroll',
                title: 'Process Payroll',
                translateKey: 'nav.collapseMenu.ProcessPayroll',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
            {
                key: 'collapseMenu.taxCalculations',
                path: '/tax/Calculations/calculations',
                title: 'Tax Calculations',
                translateKey: 'nav.collapseMenu.taxCalculations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'groupMenu',
        path: '',
        title: 'Group Menu',
        translateKey: 'nav.groupMenu.groupMenu',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'groupMenu.single',
                path: '/group-single-menu-item-view',
                title: 'Group single menu item',
                translateKey: 'nav.groupMenu.single',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'groupMenu.collapse',
                path: '',
                title: 'Group collapse menu',
                translateKey: 'nav.groupMenu.collapse.collapse',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.collapse.item1',
                        path: '/group-collapse-menu-item-view-1',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.collapse.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.collapse.item2',
                        path: '/group-collapse-menu-item-view-2',
                        title: 'Menu item 2',
                        translateKey: 'nav.groupMenu.collapse.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default navigationConfig
